/*
 * src/features/extract/standalone.js — the entry of viewer.html's classic
 * bundle (viewer.js, generated by tools/build-viewer.mjs).
 *
 * A copy of viewer.html next to your backups must work when double-clicked,
 * and a browser will not load an ES module from file://. So the standalone
 * page loads the Extract feature as one classic script instead: this entry,
 * bundled with the feature and src/features/mount.js. There is no platform
 * here — nothing to route files to, nothing to navigate.
 */
import { mount } from "./index.js";

const shell = { send() {}, toast(m) { console.log(m); }, setSub() {}, openPicker() {}, activate() {} };
mount(document.getElementById("view-viewer"), shell, { styleUrl: "src/features/extract/styles.css" });
