// Reproducible PDF.js vendoring.
//
// Generates the two PDF.js runtime files the platform ships, from the exact
// pinned pdfjs-dist package:
//   - vendor/pdf.min.js          (classic script defining window.pdfjsLib)
//   - vendor/pdf.worker.min.js   (worker bundle)
//
// Every page loads them on demand through src/services/pdf.js — one copy,
// never inlined into a page (REWRITE-PLAN.md §3.4). The ESM-only 4.x build is
// wrapped with esbuild into a classic script exposing globalThis.pdfjsLib.
// Offline behavior is preserved: no CDN URLs anywhere.
//
// Usage:
//   node tools/vendor-pdfjs.mjs           regenerate the vendor files
//   node tools/vendor-pdfjs.mjs --check   verify the vendor files match the pin
//                                         and that no page inlines a copy
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);

const PINNED = "4.2.67";
const MAIN_BANNER = `/* PDF.js v${PINNED} (Apache-2.0) — generated by tools/vendor-pdfjs.mjs from pdfjs-dist@${PINNED}; do not edit */`;
const WORKER_BANNER = `/* PDF.js worker v${PINNED} (Apache-2.0) — generated by tools/vendor-pdfjs.mjs from pdfjs-dist@${PINNED}; do not edit */`;

const VENDOR_MAIN = "vendor/pdf.min.js";
const VENDOR_WORKER = "vendor/pdf.worker.min.js";
// The other vendored runtimes, checked for their banner (the pin on record).
const OTHER_VENDOR = [
  ["vendor/jszip.min.js", "JSZip v3.10.1"],
  ["vendor/pdf-lib.min.js", "pdf-lib v1.17.1"],
];
// Pages that once carried an inline copy; none may again.
const PAGES = ["index.html", "viewer.html"];

function fail(msg) { console.error("✗ " + msg); process.exit(1); }
function okay(msg) { console.log("✓ " + msg); }

// ---------- version helpers ----------
function installedVersion() {
  return require("pdfjs-dist/package.json").version;
}
function artifactVersion(src) {
  // Every generated artifact carries the pinned version in its banner line.
  const m = src.match(/generated by tools\/vendor-pdfjs\.mjs from pdfjs-dist@(\d+\.\d+\.\d+)/);
  return m ? m[1] : null;
}

// ---------- bundle generation ----------
// The pages load the main library as a CLASSIC script (src/services/pdf.js
// injects a <script> tag), but the 4.x build is ESM-only and its webpack
// startup uses top-level await purely to unwrap Node-only async imports
// (fs/http/canvas — all skipped in browsers). Patch that one startup
// statement into a promise, drop the ESM export tail, and the result is a
// classic script that sets globalThis.pdfjsLibPromise (resolving to the API,
// which is also mirrored onto globalThis.pdfjsLib).
const STARTUP = "__webpack_exports__ = globalThis.pdfjsLib = await (globalThis.pdfjsLibPromise = __webpack_exports__);";
const STARTUP_PATCH = "globalThis.pdfjsLibPromise = Promise.resolve(__webpack_exports__).then((m) => (globalThis.pdfjsLib = m, m));";
async function bundleMain() {
  const entry = require.resolve("pdfjs-dist/legacy/build/pdf.mjs");
  let src = fs.readFileSync(entry, "utf8");
  const at = src.indexOf(STARTUP);
  if (at === -1) fail("pdf.mjs: expected webpack startup statement not found — pdfjs-dist layout changed, update tools/vendor-pdfjs.mjs");
  src = src.slice(0, at) + STARTUP_PATCH + "\n"; // everything after is ESM export plumbing
  src = "(() => {\n" + src + "\n})();";
  const { transform } = await import("esbuild");
  const out = await transform(src, { loader: "js", minify: true, target: "es2020", logLevel: "silent" });
  return MAIN_BANNER + "\n" + out.code;
}
async function bundleWorker() {
  // The worker stays the stock ESM build: pdf.js spawns it with
  // new Worker(src, { type: "module" }), where its export statement and
  // top-level await are both legal.
  const entry = require.resolve("pdfjs-dist/legacy/build/pdf.worker.min.mjs");
  return WORKER_BANNER + "\n" + fs.readFileSync(entry, "utf8");
}

// ---------- check mode ----------
function checkArtifact(name, src) {
  if (src.includes("3.11.174")) fail(`${name}: still contains PDF.js 3.11.174`);
  if (!src.includes(PINNED)) fail(`${name}: does not contain pinned version ${PINNED}`);
  okay(`${name}: pinned at ${PINNED}`);
}
function runCheck() {
  const iv = installedVersion();
  if (iv !== PINNED) fail(`installed pdfjs-dist is ${iv}, pinned ${PINNED}`);
  okay(`pdfjs-dist dependency pinned at ${PINNED}`);
  const main = fs.readFileSync(path.join(ROOT, VENDOR_MAIN), "utf8");
  const worker = fs.readFileSync(path.join(ROOT, VENDOR_WORKER), "utf8");
  checkArtifact(VENDOR_MAIN, main);
  checkArtifact(VENDOR_WORKER, worker);
  const mv = artifactVersion(main), wv = artifactVersion(worker);
  if (mv && wv && mv !== wv) fail(`main (${mv}) and worker (${wv}) versions differ`);
  okay(`main and worker artifact versions match`);
  for (const [file, banner] of OTHER_VENDOR) {
    const src = fs.readFileSync(path.join(ROOT, file), "utf8");
    if (!src.startsWith("/* " + banner)) fail(`${file}: banner does not name ${banner}`);
    okay(`${file}: ${banner}`);
  }
  for (const file of PAGES) {
    const p = path.join(ROOT, file);
    if (!fs.existsSync(p)) continue;
    const html = fs.readFileSync(p, "utf8");
    if (/<script id="pdfjs-lib">|type="text\/js-worker"|\/\* PDF\.js v\d|JSZip v3\.\d+\.\d+ - A JavaScript class|pdf-lib v1\.\d+\.\d+ \(MIT\)/.test(html)) {
      fail(`${file}: carries an inline copy of a vendored library — load it from vendor/ instead`);
    }
  }
  okay(`no page inlines a vendored library (${PAGES.length} pages)`);
  console.log("\nVENDOR CHECK PASSED ✅");
}

// ---------- main ----------
if (process.argv.includes("--check")) {
  runCheck();
} else {
  const iv = installedVersion();
  if (iv !== PINNED) fail(`installed pdfjs-dist is ${iv}; run npm ci (pinned ${PINNED})`);
  const [mainSrc, workerSrc] = await Promise.all([bundleMain(), bundleWorker()]);
  if (!mainSrc.includes(PINNED)) fail("generated main bundle lacks the pinned version string");
  if (!workerSrc.includes(PINNED)) fail("generated worker bundle lacks the pinned version string");
  fs.mkdirSync(path.join(ROOT, "vendor"), { recursive: true });
  fs.writeFileSync(path.join(ROOT, VENDOR_MAIN), mainSrc);
  fs.writeFileSync(path.join(ROOT, VENDOR_WORKER), workerSrc);
  okay(`${VENDOR_MAIN} (${(mainSrc.length / 1048576).toFixed(2)} MB)`);
  okay(`${VENDOR_WORKER} (${(workerSrc.length / 1048576).toFixed(2)} MB)`);
  console.log("\nVENDORING DONE ✅ — run with --check to verify");
}
