// Reproducible PDF.js vendoring.
//
// Generates every PDF.js runtime artifact the platform ships from the exact
// pinned pdfjs-dist package:
//   - vault/vendor/pdf.min.js          (classic script defining window.pdfjsLib)
//   - vault/vendor/pdf.worker.min.js   (worker bundle)
//   - the inline <script> bundle + <script type="text/js-worker"> block in
//     li/index.html and toolbox/index.html
//
// The apps load PDF.js as a classic script (dynamic <script> injection in the
// Vault, inline tags in LI/Toolbox), so the ESM-only 4.x build is wrapped with
// esbuild into an IIFE exposing globalThis.pdfjsLib. Offline behavior is
// preserved: no CDN URLs anywhere.
//
// Usage:
//   node tools/vendor-pdfjs.mjs           regenerate all artifacts
//   node tools/vendor-pdfjs.mjs --check   verify artifacts match the pin
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { build } from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);

const PINNED = "4.2.67";
const MAIN_BANNER = `/* PDF.js v${PINNED} (Apache-2.0) — generated by tools/vendor-pdfjs.mjs from pdfjs-dist@${PINNED}; do not edit */`;
const WORKER_BANNER = `/* PDF.js worker v${PINNED} (Apache-2.0) — generated by tools/vendor-pdfjs.mjs from pdfjs-dist@${PINNED}; do not edit */`;

const HTML_TARGETS = ["li/index.html", "toolbox/index.html"];
const VENDOR_MAIN = "vault/vendor/pdf.min.js";
const VENDOR_WORKER = "vault/vendor/pdf.worker.min.js";

function fail(msg) { console.error("✗ " + msg); process.exit(1); }
function okay(msg) { console.log("✓ " + msg); }

// ---------- version helpers ----------
function installedVersion() {
  return require("pdfjs-dist/package.json").version;
}
function artifactVersion(src) {
  // Every generated artifact carries the pinned version in its banner line.
  const m = src.match(/generated by tools\/vendor-pdfjs\.mjs from pdfjs-dist@(\d+\.\d+\.\d+)/);
  return m ? m[1] : null;
}
// A "</script" inside the bundle would terminate the inline HTML block early;
// the escaped form is byte-identical once JavaScript parses the string.
function inlineSafe(src) {
  return src.replace(/<\/script/gi, "<\\/script");
}

// ---------- bundle generation ----------
// The apps load the main library as a CLASSIC script (dynamic <script>
// injection in the Vault, inline tags in LI/Toolbox), but the 4.x build is
// ESM-only and its webpack startup uses top-level await purely to unwrap
// Node-only async imports (fs/http/canvas — all skipped in browsers).
// Patch that one startup statement into a promise, drop the ESM export tail,
// and the result is a classic script that sets globalThis.pdfjsLibPromise
// (resolving to the API, which is also mirrored onto globalThis.pdfjsLib).
const STARTUP = "__webpack_exports__ = globalThis.pdfjsLib = await (globalThis.pdfjsLibPromise = __webpack_exports__);";
const STARTUP_PATCH = "globalThis.pdfjsLibPromise = Promise.resolve(__webpack_exports__).then((m) => (globalThis.pdfjsLib = m, m));";
async function bundleMain() {
  const entry = require.resolve("pdfjs-dist/legacy/build/pdf.mjs");
  let src = fs.readFileSync(entry, "utf8");
  const at = src.indexOf(STARTUP);
  if (at === -1) fail("pdf.mjs: expected webpack startup statement not found — pdfjs-dist layout changed, update tools/vendor-pdfjs.mjs");
  src = src.slice(0, at) + STARTUP_PATCH + "\n"; // everything after is ESM export plumbing
  src = "(() => {\n" + src + "\n})();";
  const { transform } = await import("esbuild");
  const out = await transform(src, { loader: "js", minify: true, target: "es2020", logLevel: "silent" });
  return MAIN_BANNER + "\n" + out.code;
}
async function bundleWorker() {
  // The worker stays the stock ESM build: pdf.js spawns it with
  // new Worker(src, { type: "module" }), where its export statement and
  // top-level await are both legal.
  const entry = require.resolve("pdfjs-dist/legacy/build/pdf.worker.min.mjs");
  return WORKER_BANNER + "\n" + fs.readFileSync(entry, "utf8");
}

// ---------- HTML splicing ----------
// The main bundle lives in a `<script id="pdfjs-lib">…</script>` block and the
// worker source in `<script type="text/js-worker" id="pdfjs-worker">…</script>`.
// (First generation converts the legacy comment-marked v3 blocks to this form.)
function replaceBlock(html, openTagRe, replacementOpenTag, body, file, what) {
  const open = html.match(openTagRe);
  if (!open) fail(`${file}: could not find the ${what} script block`);
  const start = open.index;
  const end = html.indexOf("</script>", start + open[0].length);
  if (end === -1) fail(`${file}: unterminated ${what} script block`);
  return html.slice(0, start) + replacementOpenTag + "\n" + body + "\n</script>" + html.slice(end + "</script>".length);
}
function spliceHtml(file, mainSrc, workerSrc) {
  const p = path.join(ROOT, file);
  let html = fs.readFileSync(p, "utf8");
  html = replaceBlock(
    html,
    /<script id="pdfjs-lib">|<script>\s*\/\* PDF\.js v3\.[^\n]*/,
    '<script id="pdfjs-lib">',
    inlineSafe(mainSrc),
    file, "main PDF.js"
  );
  html = replaceBlock(
    html,
    /<script type="text\/js-worker" id="pdfjs-worker">/,
    '<script type="text/js-worker" id="pdfjs-worker">',
    inlineSafe(workerSrc),
    file, "PDF.js worker"
  );
  fs.writeFileSync(p, html);
}

// ---------- check mode ----------
function extractBlock(html, openTagRe, file, what) {
  const open = html.match(openTagRe);
  if (!open) fail(`${file}: missing ${what} script block`);
  const start = open.index + open[0].length;
  const end = html.indexOf("</script>", start);
  return html.slice(start, end);
}
function checkArtifact(name, src) {
  if (src.includes("3.11.174")) fail(`${name}: still contains PDF.js 3.11.174`);
  if (!src.includes(PINNED)) fail(`${name}: does not contain pinned version ${PINNED}`);
  okay(`${name}: pinned at ${PINNED}`);
}
function runCheck() {
  const iv = installedVersion();
  if (iv !== PINNED) fail(`installed pdfjs-dist is ${iv}, pinned ${PINNED}`);
  okay(`pdfjs-dist dependency pinned at ${PINNED}`);
  const main = fs.readFileSync(path.join(ROOT, VENDOR_MAIN), "utf8");
  const worker = fs.readFileSync(path.join(ROOT, VENDOR_WORKER), "utf8");
  checkArtifact(VENDOR_MAIN, main);
  checkArtifact(VENDOR_WORKER, worker);
  const mv = artifactVersion(main), wv = artifactVersion(worker);
  if (mv && wv && mv !== wv) fail(`main (${mv}) and worker (${wv}) versions differ`);
  okay(`main and worker artifact versions match`);
  for (const file of HTML_TARGETS) {
    const html = fs.readFileSync(path.join(ROOT, file), "utf8");
    checkArtifact(file + " (inline lib)", extractBlock(html, /<script id="pdfjs-lib">/, file, "main PDF.js"));
    checkArtifact(file + " (inline worker)", extractBlock(html, /<script type="text\/js-worker" id="pdfjs-worker">/, file, "PDF.js worker"));
  }
  console.log("\nVENDOR CHECK PASSED ✅");
}

// ---------- main ----------
if (process.argv.includes("--check")) {
  runCheck();
} else {
  const iv = installedVersion();
  if (iv !== PINNED) fail(`installed pdfjs-dist is ${iv}; run npm ci (pinned ${PINNED})`);
  const [mainSrc, workerSrc] = await Promise.all([bundleMain(), bundleWorker()]);
  if (!mainSrc.includes(PINNED)) fail("generated main bundle lacks the pinned version string");
  if (!workerSrc.includes(PINNED)) fail("generated worker bundle lacks the pinned version string");
  fs.writeFileSync(path.join(ROOT, VENDOR_MAIN), mainSrc);
  fs.writeFileSync(path.join(ROOT, VENDOR_WORKER), workerSrc);
  okay(`${VENDOR_MAIN} (${(mainSrc.length / 1048576).toFixed(2)} MB)`);
  okay(`${VENDOR_WORKER} (${(workerSrc.length / 1048576).toFixed(2)} MB)`);
  for (const file of HTML_TARGETS) {
    spliceHtml(file, mainSrc, workerSrc);
    okay(`${file}: inline lib + worker regenerated`);
  }
  console.log("\nVENDORING DONE ✅ — run with --check to verify");
}
